modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/just_dandy/issues"
license = "MIT License"

[[mods]]
    modId = "just_dandy"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "just_dandy:fluffy_dandelion"
    configBackground = "minecraft:textures/block/yellow_wool.png"
    authors = "DavigJ"
    credits = "Booleven's 1.19.2 port, and Bagel for 1.20.1 worldgen assistance"
    displayURL = "https://modrinth.com/project/just-dandy"
    displayName = "Just Dandy"
    description = '''
    Adds a little visual fluff to some biomes.
    '''

[[dependencies.just_dandy]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.just_dandy]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.just_dandy]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"